### ISSUE TITLE
use a default window (in sec) for preproc report spectrum

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/oslpy#112]
MNE's plot_psd uses a default window of `n_fft = 2048`, so in terms of samples. This means that depending on how much you resample your data, the spectral resolution can be higher or lower. I think it'd be better if we use a default option of a number of seconds, i.e. 2 seconds.

i.e. `raw.plot_psd(n_fft=int(raw.info['sfreq']*2))`

As a side note, we could decide to adopt @AJQuinn 's square root of f plot, which I quite like.

**Comment by matsvanes** [comment]
I also just noticed that the power spectra in the report sometimes show the gradiometers in the first row, and sometimes the magnetometers. Small thing, but consistency would be nice

**Comment by cgohil8** [comment]
I agree 2 s is probably better, which would give us a resolution of 0.5 Hz. In this issue let's just change the default n_fft. I'll fix the PSDs in the report in this issue: https://github.com/OHBA-analysis/oslpy/issues/70.

**Comment by cgohil8** [comment]
Pull request https://github.com/OHBA-analysis/oslpy/pull/116 fixes the order of sensors and the default n_fft. The change in x-axis scale to 1/f was not added. Please reopen this issue/create a new issue if we want to change the x-axis of the PSDs.
