### ISSUE TITLE
report directory naming convention

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/oslpy#113]
Not sure whether this is a bug or a feature, but when we run (batch) preprocessing, reports will be created for each file in a directory like this (for the raw (maxfiltered) file named `sub-001_task-rest_tsss.fif`):
`report/sub-001_task-rest_tsss`

However, if the creation of the report fails for whatever reason, and you run the report from scratch using `osl.report.gen_report_from_fif`, it will as a default create files in directories named `report/sub-001_task-rest_tsss_preproc_raw`. I think the options should be consistent, and probably should have the latter naming convention.

**Comment by cgohil8** [comment]
Yeah, i agree, this should be straightforward to fix. I'm happy to address this one.
