### ISSUE TITLE
fslpy.utils.filetree is deprecated

### ISSUE THREAD

**Issue by evanr70** [OHBA-analysis/oslpy#2]
`fsl.utils.filetree` is deprecated according to the fslpy changelog. It's now a separate package hosted here: https://pypi.org/project/file-tree/

**Comment by AJQuinn** [comment]
ah - well spotted, hadn't noticed that. Will fix in the next update!

**Comment by AJQuinn** [comment]
This has been updated in https://github.com/OHBA-analysis/oslpy/commit/de4196d2793fd4215d4cd90169d1899260203369

Minimal functionality for the moment but should work if you update to main. Thanks for the tip.
