### ISSUE TITLE
Feature request: generate report with existing plots

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/oslpy#28]
Currently, the report function creates an html with only the files that were given as inputfiles to the function call. That means that if you've done a big batch process before, for which you have a collective report, and you get new data, you would need to recreate all previous plots if you want to "update" the collective report. 
It would be good if we can make an `overwrite` option in the report, that if `False`, will first check whether the plots for this specific data already exist and if so, skip the creation of those plots (and thus save computation power and time), and in the end generate the report with all existing and new plots in it.

**Comment by cgohil8** [comment]
Resolved in https://github.com/OHBA-analysis/oslpy/pull/34. We now have a function https://github.com/OHBA-analysis/oslpy/blob/main/osl/report/raw_report.py#L175, which given a directory containing the HTML data will create a webpage.
