### ISSUE TITLE
Suggestions for report improvement

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/oslpy#39]
- remember the tab in the previous file when you go to the next (or have a toggle that can control whether to do so or not)
- still have a list of all files somewhere so you can quickly go to a specific file
- in the window indicate how many files there are (e.g. 63/114 files)

**Comment by cgohil8** [comment]
How about a 2 page report:
- 1st page is a list of hyperlinks (filenames). You click a filename and it takes you to the panel (2nd page).
- Add a "back to filename list" button you can click to go back to the list
?

**Comment by matsvanes** [comment]
I think that would work (for my second point above)! Would be great if the arrows also still work. Suggestions in points 1 and 3 could be added to this I recon?

**Comment by cgohil8** [comment]
If you checkout the new reporting branch: 'report', then you can regenerate the HTML using the figures you've already created for the maxfiltered data. I think something like the following should be fine:

`from osl.report.raw_report import gen_html_page

gen_html_page("/path/to/report/dir")`

What do you think of the new report. I added 2/3 features, adding a long file of files might be a bit ugly, but I can do this if you still think it's helpful?

**Comment by cgohil8** [comment]
Actually, the latest report lets you navigate to a file based on an ID number, e.g. X out of Y files. But you don't know what fif file X corresponds to so many we do need to have a list somewhere linking the IDs to the names.

**Comment by cgohil8** [comment]
Alright, I've added all 3 features. @matsvanes Do you want to generate a new report (with the code above) and see if you're happy with the report, then i'll merge.
