### ISSUE TITLE
Filtering before ICA

### ISSUE THREAD

**Issue by ricsinaruto** [OHBA-analysis/oslpy#4]
Hi,

MNE recommends a highpass filter at 1Hz before doing ICA:
https://mne.tools/stable/auto_tutorials/preprocessing/40_artifact_correction_ica.html#filtering-to-remove-slow-drifts

However, this is not currently present in the code:
https://github.com/OHBA-analysis/oslpy/blob/main/osl/preprocessing/_mne_wrappers.py#L312

My solution would be to check what highpass filtering had been done on the raw object and if it's less than 1Hz to automatically do a highpass filter on a copy of the raw object as recommended by MNE.

Let me know what you think, I can implement it if you agree.

**Comment by AJQuinn** [comment]
Hey sorry about delay - we're actually doing this now!
