### ISSUE TITLE
Argument ordering in preprocessing functions

### ISSUE THREAD

**Issue by cgohil8** [OHBA-analysis/oslpy#51]
The order of the arguments for run_proc_chain is:
`def run_proc_chain(infile, config, ...):`
whereas for run_proc_batch it is:
`def run_proc_batch(config, files, ...):`
note the config and input file(s) have swapped.

We should maybe change the order of the arguments in one of these functions to make sure it's consistent. This will break existing scripts, but maybe worth doing now rather than later.

What do you think @AJQuinn @matsvanes

**Comment by matsvanes** [comment]
I completely agree. Haven't spotted this before, but best have a consistency with the config and files - also holds for the source recon stage. It's better we fix it now that there's only few people using it

**Comment by cgohil8** [comment]
@AJQuinn, if you also agree I can make the change.
