### ISSUE TITLE
Report doesn't show bad channels

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/oslpy#54]
Bad channels are not annotated in the report

**Comment by cgohil8** [comment]
I think this is a problem when you have multiple channel types, i've preprocessed EEG data where it does correctly highlight bad channels:
![bad_chans](https://user-images.githubusercontent.com/53237863/190437224-59b4ddac-9ea0-4afe-891f-2ed46d7f2509.png)

**Comment by matsvanes** [comment]
I think so, yes. I'm working on this now
