### ISSUE TITLE
Separate batch "coregister" into separate surface, coregister and forward to match the underlying functions

### ISSUE THREAD

**Issue by woolrich** [OHBA-analysis/oslpy#74]
Separate batch "coregister" into separate surface, coregister and forward to match the underlying functions
compute_surfaces()
coreg()
forward_model()

**Comment by cgohil8** [comment]
So do you mean have the option so have the following config for example:

```
config = """
- compute_surfaces: {include_nose: true}
- coreg: {use_headshape: true, use_nose: true}
- forward_model: {}
"""
```
